// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payments.API.Data;

#nullable disable

namespace payments_api.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("payments_api.Models.Card", b =>
                {
                    b.Property<int>("Card_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Card_Id"));

                    b.Property<string>("Card_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Card_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Expiration_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Card_Id");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
